#!/usr/bin/env python

from chdrft.waf.opa import WafBuilder


x = WafBuilder(globals())
x.register_libs(x.libs.Common_N, x.libs.MathCommon_N, x.libs.Algo_N, x.libs.MathGame_N, x.packages.Eigen)

x.auto()
x.setup()
