# This file was *autogenerated* from the file p88.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_12012 = Integer(12012); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_12000 = Integer(12000); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_1909 = Integer(1909); _sage_const_1864 = Integer(1864)

def euler_p88():
  maxk= _sage_const_12012 
  res=_sage_const_0 
  di
  for i in range(_sage_const_2 ,maxk):
    s1 = _sage_const_0 
    cnt = _sage_const_0 
    for f in list(factor(i)):
      s1 += f[_sage_const_0 ] * f[_sage_const_1 ]
      cnt +=_sage_const_0  
    if i-s1 <=_sage_const_12000 : res+=_sage_const_1 
  print(res)

def euler_p228():
  (low, high) = (_sage_const_1864 , _sage_const_1909 )
  (low, high) = (_sage_const_3 , _sage_const_4 )
  s = set()
  for i in range(low, high+_sage_const_1 ):
    for k in range(i):
      m = _sage_const_2 *k
      d = gcd(m, i)
      s.add((m / d, i / d))
  print(len(s))

euler_p228()


