# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_14 = Integer(14)
def search(state, cur, last):
    if state == _sage_const_0 :
        return _sage_const_1  if cur == last else _sage_const_0 
    # print state, cur, last
    ret = _sage_const_0 
    for i in range(-_sage_const_3 , _sage_const_4 ):
        v = cur + i
        if _sage_const_0  <= v <= last and (state >> v & _sage_const_1 ) == _sage_const_1 :
            ret += search(state ^ (_sage_const_1  << v), v, last)
    return ret

def main():
    # ans = []
    # for n in range(1, 20):
    #     cnt = search((1 << n) - 2, 0, n - 1)
    #     ans += [cnt]
    #     print n, cnt

    ans = [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_2 , _sage_const_6 ] #, 14, 28, 56, 118, 254, 541, 1140, 2401, 5074, 10738, 22711, 48001, 101447, 214446, 453355, 958395, 2025963, 4282685, 9053286, 19138115, 40456779, 85522862]
    # for i in range(1, len(ans)):
    #     ans[i] += ans[i - 1]
    # for i in range(8, 50):
    #     next = ans[i - 1] * 2 - ans[i - 2] + ans[i - 3] * 2 + ans[i - 4] + ans[i - 5] - ans[i - 7] - ans[i - 8]
    #     ans += [next]
        # (-1, -1, 0, 1, 1, 2, -1, 2)
    equ = -_sage_const_1  - x + x**_sage_const_3  + x**_sage_const_4  + _sage_const_2  * x**_sage_const_5  - x**_sage_const_6  + _sage_const_2  * x**_sage_const_7  - x**_sage_const_8 
    print equ

    coef = [-_sage_const_1 , -_sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_2 , -_sage_const_1 , _sage_const_2 ]
    idx = {}
    for i in range(_sage_const_8 ):
        for j in range(i, _sage_const_8 ):
            for k in range(j, _sage_const_8 ):
                cur = len(idx)
                idx[(i, j, k)] = cur
    cur = len(idx)
    idx['sum'] = cur

    size = len(idx)
    mat = [[_sage_const_0 ] * size for i in range(size)]
    init = [_sage_const_0 ] * size
    print 'matrix size = %d' % (size)

    mat[idx['sum']][idx['sum']] += _sage_const_1 
    mat[idx['sum']][idx[(_sage_const_4 , _sage_const_4 , _sage_const_4 )]] += _sage_const_1 

    for i in range(_sage_const_8 ):
        for j in range(i, _sage_const_8 ):
            for k in range(j, _sage_const_8 ):
                cur = idx[(i, j, k)]

                def dfs(L, Y, c):
                    if len(L) == _sage_const_0 :
                        y = tuple(sorted(Y))
                        src = idx[y]
                        mat[cur][src] += c
                        return
                    x, xs = L[_sage_const_0 ], L[_sage_const_1 :]
                    if x != _sage_const_7 :
                        dfs(xs, Y + (x + _sage_const_1 , ), c)
                    else:
                        for i, nc in enumerate(coef):
                            dfs(xs, Y + (i, ), c * nc)

                dfs([i, j, k], (), _sage_const_1 )

    for i in range(_sage_const_8 ):
        for j in range(i, _sage_const_8 ):
            for k in range(j, _sage_const_8 ):
                init[idx[(i, j, k)]] += ans[i] * ans[j] * ans[k]

    R = Integers(_sage_const_10 **_sage_const_9 )
    mat = matrix(R, mat)
    vec = vector(R, init)
    next = mat**(_sage_const_10 **_sage_const_14 ) * vec
    # for i in range(8):
    #     for j in range(i, 8):
    #         for k in range(j, 8):
    #             print i, j, k, next[idx[(i, j, k)]]
    print next

    # print roots(equ)
    # for width in range(6, 25):
    #     w, b = [], []
    #     for i in range(width):
    #         w += [powered[i:i + width]]
    #         b += [powered[i + width]]
    #     coef = matrix(w)^-1 * vector(b)
    #     print coef, vector(powered[width : width * 2]) * coef, powered[width * 2]
    return

main()
